#!/bin/sh

# Copyright 2015 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
################################################################################

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

APP_HOME="$(cd "$(dirname "$0")"; pwd -P)"
APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/bin/java" ] ; then
        JAVACMD="$JAVA_HOME/bin/java"
    else
        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
        exit 1
    fi
else
    JAVACMD="java"
fi

# Increase the maximum file descriptors if we can.
MAX_FD="maximum"
if [ "$CYGWIN" = "true" ] || [ "$MSYS" = "true" ] ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    JAVACMD=$(cygpath --unix "$JAVACMD")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
fi

# Collect all arguments for the java command.
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

# For Darwin/OSX, add options to deal with the system java.
if [ "Darwin" = "$(uname)" ] ; then
    if [ "$HOME" = "$PWD" ] ; then
        cd "$APP_HOME"
    fi
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
